#! /bin/bash
options=(
    style=round
    width=6.0
    hidpi=on
    activate_color=0xc0e2e2e3
    inactivate_color=0xc02c2e34
    background_color=0x302c2e34
    blur_radius=25
)

borders "${options[@]}"
